apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: leister/lifebank-hapi:latest
              args:
                - /bin/sh
                - -c
                - node "/app/src/cron-jobs/monthly-transaction.js"
          restartPolicy: OnFailure
