apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: dev-lifebank-hapi
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - "node /usr/app/src/cron-jobs/monthly-transaction.js"
          restartPolicy: OnFailure
