apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lifebank-storage
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
