name: Build images from latest main branch

on:
  push:
    branches:
      - main
jobs:
  create-main-image:
    name: env
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build new images and push
        run: |
          make \
            build-docker-images \
            push-docker-images
        env:
          # global
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          EOS_PRIV_KEY: ${{ secrets.EOS_PRIV }}
          MAIL_PASSWORD: ${{ secrets.MAIL_SECRET }}
          NAMESPACE: lifebank
          STAGE: dev
          APP_NAME: lifebank
          INGRESS_HOST: lifebank.io
          INGRESS_GRAPHQL_HOST: graphql.lifebank.io

          #postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_SECRET }}

          #webapp
          PORT: 80
          REACT_APP_EOS_API_HOST: lifebank.eosio.cr
          REACT_APP_EOS_API_PORT: 443
          REACT_APP_EOS_API_PROTOCOL: https
          REACT_APP_EOS_CHAIN_ID: ${{ secrets.REACT_APP_EOS_CHAIN_ID }}
          REACT_APP_HASURA_URL: http://localhost:8080/v1/graphql
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
          REACT_CAPTCHA_KEY: ${{ secrets.CAPTCHA_SECRET }}
          REACT_APP_BLOCK_EXPLORER_URL: block_explorer_url

          # hasura
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.HASURA_GRAPHQL_DATABASE_URL }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_SECRET }}
